export const countriesData = [
  {
    name: 'Afghanistan',
    alpha2Code: 'AF',
    callingCode: '+93',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png',
    currencyCode: 'AFN',
    currencyName: 'Afghan afghani',
    currencySymbol: '؋',
  },
  {
    name: 'Åland Islands',
    alpha2Code: 'AX',
    callingCode: '+35818',
    flag: 'https://flagcdn.com/w320/ax.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Albania',
    alpha2Code: 'AL',
    callingCode: '+355',
    flag: 'https://flagcdn.com/w320/al.png',
    currencyCode: 'ALL',
    currencyName: 'Albanian lek',
    currencySymbol: 'L',
  },
  {
    name: 'Algeria',
    alpha2Code: 'DZ',
    callingCode: '+213',
    flag: 'https://flagcdn.com/w320/dz.png',
    currencyCode: 'DZD',
    currencyName: 'Algerian dinar',
    currencySymbol: 'د.ج',
  },
  {
    name: 'American Samoa',
    alpha2Code: 'AS',
    callingCode: '+1684',
    flag: 'https://flagcdn.com/w320/as.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Andorra',
    alpha2Code: 'AD',
    callingCode: '+376',
    flag: 'https://flagcdn.com/w320/ad.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Angola',
    alpha2Code: 'AO',
    callingCode: '+244',
    flag: 'https://flagcdn.com/w320/ao.png',
    currencyCode: 'AOA',
    currencyName: 'Angolan kwanza',
    currencySymbol: 'Kz',
  },
  {
    name: 'Anguilla',
    alpha2Code: 'AI',
    callingCode: '+1264',
    flag: 'https://flagcdn.com/w320/ai.png',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
  },
  {
    name: 'Antarctica',
    alpha2Code: 'AQ',
    callingCode: '',
    flag: 'https://flagcdn.com/w320/aq.png',
    currencyCode: '',
    currencyName: '',
    currencySymbol: '',
  },
  {
    name: 'Antigua and Barbuda',
    alpha2Code: 'AG',
    callingCode: '+1268',
    flag: 'https://flagcdn.com/w320/ag.png',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
  },
  {
    name: 'Argentina',
    alpha2Code: 'AR',
    callingCode: '+54',
    flag: 'https://flagcdn.com/w320/ar.png',
    currencyCode: 'ARS',
    currencyName: 'Argentine peso',
    currencySymbol: '$',
  },
  {
    name: 'Armenia',
    alpha2Code: 'AM',
    callingCode: '+374',
    flag: 'https://flagcdn.com/w320/am.png',
    currencyCode: 'AMD',
    currencyName: 'Armenian dram',
    currencySymbol: '֏',
  },
  {
    name: 'Aruba',
    alpha2Code: 'AW',
    callingCode: '+297',
    flag: 'https://flagcdn.com/w320/aw.png',
    currencyCode: 'AWG',
    currencyName: 'Aruban florin',
    currencySymbol: 'ƒ',
  },
  {
    name: 'Australia',
    alpha2Code: 'AU',
    callingCode: '+61',
    flag: 'https://flagcdn.com/w320/au.png',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Austria',
    alpha2Code: 'AT',
    callingCode: '+43',
    flag: 'https://flagcdn.com/w320/at.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Azerbaijan',
    alpha2Code: 'AZ',
    callingCode: '+994',
    flag: 'https://flagcdn.com/w320/az.png',
    currencyCode: 'AZN',
    currencyName: 'Azerbaijani manat',
    currencySymbol: '₼',
  },
  {
    name: 'Bahamas',
    alpha2Code: 'BS',
    callingCode: '+1242',
    flag: 'https://flagcdn.com/w320/bs.png',
    currencyCode: 'BSD',
    currencyName: 'Bahamian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Bahrain',
    alpha2Code: 'BH',
    callingCode: '+973',
    flag: 'https://flagcdn.com/w320/bh.png',
    currencyCode: 'BHD',
    currencyName: 'Bahraini dinar',
    currencySymbol: '.د.ب',
  },
  {
    name: 'Bangladesh',
    alpha2Code: 'BD',
    callingCode: '+880',
    flag: 'https://flagcdn.com/w320/bd.png',
    currencyCode: 'BDT',
    currencyName: 'Bangladeshi taka',
    currencySymbol: '৳',
  },
  {
    name: 'Barbados',
    alpha2Code: 'BB',
    callingCode: '+1246',
    flag: 'https://flagcdn.com/w320/bb.png',
    currencyCode: 'BBD',
    currencyName: 'Barbadian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Belarus',
    alpha2Code: 'BY',
    callingCode: '+375',
    flag: 'https://flagcdn.com/w320/by.png',
    currencyCode: 'BYN',
    currencyName: 'Belarusian ruble',
    currencySymbol: 'Br',
  },
  {
    name: 'Belgium',
    alpha2Code: 'BE',
    callingCode: '+32',
    flag: 'https://flagcdn.com/w320/be.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Belize',
    alpha2Code: 'BZ',
    callingCode: '+501',
    flag: 'https://flagcdn.com/w320/bz.png',
    currencyCode: 'BZD',
    currencyName: 'Belize dollar',
    currencySymbol: '$',
  },
  {
    name: 'Benin',
    alpha2Code: 'BJ',
    callingCode: '+229',
    flag: 'https://flagcdn.com/w320/bj.png',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Bermuda',
    alpha2Code: 'BM',
    callingCode: '+1441',
    flag: 'https://flagcdn.com/w320/bm.png',
    currencyCode: 'BMD',
    currencyName: 'Bermudian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Bhutan',
    alpha2Code: 'BT',
    callingCode: '+975',
    flag: 'https://flagcdn.com/w320/bt.png',
    currencyCode: 'BTN',
    currencyName: 'Bhutanese ngultrum',
    currencySymbol: 'Nu.',
  },
  {
    name: 'Bolivia',
    alpha2Code: 'BO',
    callingCode: '+591',
    flag: 'https://flagcdn.com/w320/bo.png',
    currencyCode: 'BOB',
    currencyName: 'Bolivian boliviano',
    currencySymbol: 'Bs.',
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2Code: 'BA',
    callingCode: '+387',
    flag: 'https://flagcdn.com/w320/ba.png',
    currencyCode: 'BAM',
    currencyName: 'Bosnia and Herzegovina convertible mark',
    currencySymbol: '',
  },
  {
    name: 'Botswana',
    alpha2Code: 'BW',
    callingCode: '+267',
    flag: 'https://flagcdn.com/w320/bw.png',
    currencyCode: 'BWP',
    currencyName: 'Botswana pula',
    currencySymbol: 'P',
  },
  {
    name: 'Bouvet Island',
    alpha2Code: 'BV',
    callingCode: '+47',
    flag: 'https://flagcdn.com/w320/bv.png',
    currencyCode: '',
    currencyName: '',
    currencySymbol: '',
  },
  {
    name: 'Brazil',
    alpha2Code: 'BR',
    callingCode: '+55',
    flag: 'https://flagcdn.com/w320/br.png',
    currencyCode: 'BRL',
    currencyName: 'Brazilian real',
    currencySymbol: 'R$',
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2Code: 'IO',
    callingCode: '+246',
    flag: 'https://flagcdn.com/w320/io.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'British Virgin Islands',
    alpha2Code: 'VG',
    callingCode: '+1284',
    flag: 'https://flagcdn.com/w320/vg.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Brunei',
    alpha2Code: 'BN',
    callingCode: '+673',
    flag: 'https://flagcdn.com/w320/bn.png',
    currencyCode: 'BND',
    currencyName: 'Brunei dollar',
    currencySymbol: '$',
  },
  {
    name: 'Bulgaria',
    alpha2Code: 'BG',
    callingCode: '+359',
    flag: 'https://flagcdn.com/w320/bg.png',
    currencyCode: 'BGN',
    currencyName: 'Bulgarian lev',
    currencySymbol: 'лв',
  },
  {
    name: 'Burkina Faso',
    alpha2Code: 'BF',
    callingCode: '+226',
    flag: 'https://flagcdn.com/w320/bf.png',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Burundi',
    alpha2Code: 'BI',
    callingCode: '+257',
    flag: 'https://flagcdn.com/w320/bi.png',
    currencyCode: 'BIF',
    currencyName: 'Burundian franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Cambodia',
    alpha2Code: 'KH',
    callingCode: '+855',
    flag: 'https://flagcdn.com/w320/kh.png',
    currencyCode: 'KHR',
    currencyName: 'Cambodian riel',
    currencySymbol: '៛',
  },
  {
    name: 'Cameroon',
    alpha2Code: 'CM',
    callingCode: '+237',
    flag: 'https://flagcdn.com/w320/cm.png',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Canada',
    alpha2Code: 'CA',
    callingCode: '+1',
    flag: 'https://flagcdn.com/w320/ca.png',
    currencyCode: 'CAD',
    currencyName: 'Canadian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Cape Verde',
    alpha2Code: 'CV',
    callingCode: '+238',
    flag: 'https://flagcdn.com/w320/cv.png',
    currencyCode: 'CVE',
    currencyName: 'Cape Verdean escudo',
    currencySymbol: 'Esc',
  },
  {
    name: 'Caribbean Netherlands',
    alpha2Code: 'BQ',
    callingCode: '+599',
    flag: 'https://flagcdn.com/w320/bq.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Cayman Islands',
    alpha2Code: 'KY',
    callingCode: '+1345',
    flag: 'https://flagcdn.com/w320/ky.png',
    currencyCode: 'KYD',
    currencyName: 'Cayman Islands dollar',
    currencySymbol: '$',
  },
  {
    name: 'Central African Republic',
    alpha2Code: 'CF',
    callingCode: '+236',
    flag: 'https://flagcdn.com/w320/cf.png',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Chad',
    alpha2Code: 'TD',
    callingCode: '+235',
    flag: 'https://flagcdn.com/w320/td.png',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Chile',
    alpha2Code: 'CL',
    callingCode: '+56',
    flag: 'https://flagcdn.com/w320/cl.png',
    currencyCode: 'CLP',
    currencyName: 'Chilean peso',
    currencySymbol: '$',
  },
  {
    name: 'China',
    alpha2Code: 'CN',
    callingCode: '+86',
    flag: 'https://flagcdn.com/w320/cn.png',
    currencyCode: 'CNY',
    currencyName: 'Chinese yuan',
    currencySymbol: '¥',
  },
  {
    name: 'Christmas Island',
    alpha2Code: 'CX',
    callingCode: '+61',
    flag: 'https://flagcdn.com/w320/cx.png',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2Code: 'CC',
    callingCode: '+61',
    flag: 'https://flagcdn.com/w320/cc.png',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Colombia',
    alpha2Code: 'CO',
    callingCode: '+57',
    flag: 'https://flagcdn.com/w320/co.png',
    currencyCode: 'COP',
    currencyName: 'Colombian peso',
    currencySymbol: '$',
  },
  {
    name: 'Comoros',
    alpha2Code: 'KM',
    callingCode: '+269',
    flag: 'https://flagcdn.com/w320/km.png',
    currencyCode: 'KMF',
    currencyName: 'Comorian franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Cook Islands',
    alpha2Code: 'CK',
    callingCode: '+682',
    flag: 'https://flagcdn.com/w320/ck.png',
    currencyCode: 'CKD',
    currencyName: 'Cook Islands dollar',
    currencySymbol: '$',
  },
  {
    name: 'Costa Rica',
    alpha2Code: 'CR',
    callingCode: '+506',
    flag: 'https://flagcdn.com/w320/cr.png',
    currencyCode: 'CRC',
    currencyName: 'Costa Rican colón',
    currencySymbol: '₡',
  },
  {
    name: 'Croatia',
    alpha2Code: 'HR',
    callingCode: '+385',
    flag: 'https://flagcdn.com/w320/hr.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Cuba',
    alpha2Code: 'CU',
    callingCode: '+53',
    flag: 'https://flagcdn.com/w320/cu.png',
    currencyCode: 'CUC',
    currencyName: 'Cuban convertible peso',
    currencySymbol: '$',
  },
  {
    name: 'Curaçao',
    alpha2Code: 'CW',
    callingCode: '+599',
    flag: 'https://flagcdn.com/w320/cw.png',
    currencyCode: 'ANG',
    currencyName: 'Netherlands Antillean guilder',
    currencySymbol: 'ƒ',
  },
  {
    name: 'Cyprus',
    alpha2Code: 'CY',
    callingCode: '+357',
    flag: 'https://flagcdn.com/w320/cy.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Czechia',
    alpha2Code: 'CZ',
    callingCode: '+420',
    flag: 'https://flagcdn.com/w320/cz.png',
    currencyCode: 'CZK',
    currencyName: 'Czech koruna',
    currencySymbol: 'Kč',
  },
  {
    name: 'Denmark',
    alpha2Code: 'DK',
    callingCode: '+45',
    flag: 'https://flagcdn.com/w320/dk.png',
    currencyCode: 'DKK',
    currencyName: 'Danish krone',
    currencySymbol: 'kr',
  },
  {
    name: 'Djibouti',
    alpha2Code: 'DJ',
    callingCode: '+253',
    flag: 'https://flagcdn.com/w320/dj.png',
    currencyCode: 'DJF',
    currencyName: 'Djiboutian franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Dominica',
    alpha2Code: 'DM',
    callingCode: '+1767',
    flag: 'https://flagcdn.com/w320/dm.png',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
  },
  {
    name: 'Dominican Republic',
    alpha2Code: 'DO',
    callingCode: '+1809',
    flag: 'https://flagcdn.com/w320/do.png',
    currencyCode: 'DOP',
    currencyName: 'Dominican peso',
    currencySymbol: '$',
  },
  {
    name: 'DR Congo',
    alpha2Code: 'CD',
    callingCode: '+243',
    flag: 'https://flagcdn.com/w320/cd.png',
    currencyCode: 'CDF',
    currencyName: 'Congolese franc',
    currencySymbol: 'FC',
  },
  {
    name: 'Ecuador',
    alpha2Code: 'EC',
    callingCode: '+593',
    flag: 'https://flagcdn.com/w320/ec.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Egypt',
    alpha2Code: 'EG',
    callingCode: '+20',
    flag: 'https://flagcdn.com/w320/eg.png',
    currencyCode: 'EGP',
    currencyName: 'Egyptian pound',
    currencySymbol: '£',
  },
  {
    name: 'El Salvador',
    alpha2Code: 'SV',
    callingCode: '+503',
    flag: 'https://flagcdn.com/w320/sv.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Equatorial Guinea',
    alpha2Code: 'GQ',
    callingCode: '+240',
    flag: 'https://flagcdn.com/w320/gq.png',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Eritrea',
    alpha2Code: 'ER',
    callingCode: '+291',
    flag: 'https://flagcdn.com/w320/er.png',
    currencyCode: 'ERN',
    currencyName: 'Eritrean nakfa',
    currencySymbol: 'Nfk',
  },
  {
    name: 'Estonia',
    alpha2Code: 'EE',
    callingCode: '+372',
    flag: 'https://flagcdn.com/w320/ee.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Eswatini',
    alpha2Code: 'SZ',
    callingCode: '+268',
    flag: 'https://flagcdn.com/w320/sz.png',
    currencyCode: 'SZL',
    currencyName: 'Swazi lilangeni',
    currencySymbol: 'L',
  },
  {
    name: 'Ethiopia',
    alpha2Code: 'ET',
    callingCode: '+251',
    flag: 'https://flagcdn.com/w320/et.png',
    currencyCode: 'ETB',
    currencyName: 'Ethiopian birr',
    currencySymbol: 'Br',
  },
  {
    name: 'Falkland Islands',
    alpha2Code: 'FK',
    callingCode: '+500',
    flag: 'https://flagcdn.com/w320/fk.png',
    currencyCode: 'FKP',
    currencyName: 'Falkland Islands pound',
    currencySymbol: '£',
  },
  {
    name: 'Faroe Islands',
    alpha2Code: 'FO',
    callingCode: '+298',
    flag: 'https://flagcdn.com/w320/fo.png',
    currencyCode: 'DKK',
    currencyName: 'Danish krone',
    currencySymbol: 'kr',
  },
  {
    name: 'Fiji',
    alpha2Code: 'FJ',
    callingCode: '+679',
    flag: 'https://flagcdn.com/w320/fj.png',
    currencyCode: 'FJD',
    currencyName: 'Fijian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Finland',
    alpha2Code: 'FI',
    callingCode: '+358',
    flag: 'https://flagcdn.com/w320/fi.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'France',
    alpha2Code: 'FR',
    callingCode: '+33',
    flag: 'https://flagcdn.com/w320/fr.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'French Guiana',
    alpha2Code: 'GF',
    callingCode: '+594',
    flag: 'https://flagcdn.com/w320/gf.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'French Polynesia',
    alpha2Code: 'PF',
    callingCode: '+689',
    flag: 'https://flagcdn.com/w320/pf.png',
    currencyCode: 'XPF',
    currencyName: 'CFP franc',
    currencySymbol: '₣',
  },
  {
    name: 'French Southern and Antarctic Lands',
    alpha2Code: 'TF',
    callingCode: '+262',
    flag: 'https://flagcdn.com/w320/tf.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Gabon',
    alpha2Code: 'GA',
    callingCode: '+241',
    flag: 'https://flagcdn.com/w320/ga.png',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Gambia',
    alpha2Code: 'GM',
    callingCode: '+220',
    flag: 'https://flagcdn.com/w320/gm.png',
    currencyCode: 'GMD',
    currencyName: 'dalasi',
    currencySymbol: 'D',
  },
  {
    name: 'Georgia',
    alpha2Code: 'GE',
    callingCode: '+995',
    flag: 'https://flagcdn.com/w320/ge.png',
    currencyCode: 'GEL',
    currencyName: 'lari',
    currencySymbol: '₾',
  },
  {
    name: 'Germany',
    alpha2Code: 'DE',
    callingCode: '+49',
    flag: 'https://flagcdn.com/w320/de.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Ghana',
    alpha2Code: 'GH',
    callingCode: '+233',
    flag: 'https://flagcdn.com/w320/gh.png',
    currencyCode: 'GHS',
    currencyName: 'Ghanaian cedi',
    currencySymbol: '₵',
  },
  {
    name: 'Gibraltar',
    alpha2Code: 'GI',
    callingCode: '+350',
    flag: 'https://flagcdn.com/w320/gi.png',
    currencyCode: 'GIP',
    currencyName: 'Gibraltar pound',
    currencySymbol: '£',
  },
  {
    name: 'Greece',
    alpha2Code: 'GR',
    callingCode: '+30',
    flag: 'https://flagcdn.com/w320/gr.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Greenland',
    alpha2Code: 'GL',
    callingCode: '+299',
    flag: 'https://flagcdn.com/w320/gl.png',
    currencyCode: 'DKK',
    currencyName: 'krone',
    currencySymbol: 'kr.',
  },
  {
    name: 'Grenada',
    alpha2Code: 'GD',
    callingCode: '+1473',
    flag: 'https://flagcdn.com/w320/gd.png',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
  },
  {
    name: 'Guadeloupe',
    alpha2Code: 'GP',
    callingCode: '+590',
    flag: 'https://flagcdn.com/w320/gp.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Guam',
    alpha2Code: 'GU',
    callingCode: '+1671',
    flag: 'https://flagcdn.com/w320/gu.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Guatemala',
    alpha2Code: 'GT',
    callingCode: '+502',
    flag: 'https://flagcdn.com/w320/gt.png',
    currencyCode: 'GTQ',
    currencyName: 'Guatemalan quetzal',
    currencySymbol: 'Q',
  },
  {
    name: 'Guernsey',
    alpha2Code: 'GG',
    callingCode: '+44',
    flag: 'https://flagcdn.com/w320/gg.png',
    currencyCode: 'GBP',
    currencyName: 'British pound',
    currencySymbol: '£',
  },
  {
    name: 'Guinea',
    alpha2Code: 'GN',
    callingCode: '+224',
    flag: 'https://flagcdn.com/w320/gn.png',
    currencyCode: 'GNF',
    currencyName: 'Guinean franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Guinea-Bissau',
    alpha2Code: 'GW',
    callingCode: '+245',
    flag: 'https://flagcdn.com/w320/gw.png',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Guyana',
    alpha2Code: 'GY',
    callingCode: '+592',
    flag: 'https://flagcdn.com/w320/gy.png',
    currencyCode: 'GYD',
    currencyName: 'Guyanese dollar',
    currencySymbol: '$',
  },
  {
    name: 'Haiti',
    alpha2Code: 'HT',
    callingCode: '+509',
    flag: 'https://flagcdn.com/w320/ht.png',
    currencyCode: 'HTG',
    currencyName: 'Haitian gourde',
    currencySymbol: 'G',
  },
  {
    name: 'Heard Island and McDonald Islands',
    alpha2Code: 'HM',
    callingCode: '',
    flag: 'https://flagcdn.com/w320/hm.png',
    currencyCode: '',
    currencyName: '',
    currencySymbol: '',
  },
  {
    name: 'Honduras',
    alpha2Code: 'HN',
    callingCode: '+504',
    flag: 'https://flagcdn.com/w320/hn.png',
    currencyCode: 'HNL',
    currencyName: 'Honduran lempira',
    currencySymbol: 'L',
  },
  {
    name: 'Hong Kong',
    alpha2Code: 'HK',
    callingCode: '+852',
    flag: 'https://flagcdn.com/w320/hk.png',
    currencyCode: 'HKD',
    currencyName: 'Hong Kong dollar',
    currencySymbol: '$',
  },
  {
    name: 'Hungary',
    alpha2Code: 'HU',
    callingCode: '+36',
    flag: 'https://flagcdn.com/w320/hu.png',
    currencyCode: 'HUF',
    currencyName: 'Hungarian forint',
    currencySymbol: 'Ft',
  },
  {
    name: 'Iceland',
    alpha2Code: 'IS',
    callingCode: '+354',
    flag: 'https://flagcdn.com/w320/is.png',
    currencyCode: 'ISK',
    currencyName: 'Icelandic króna',
    currencySymbol: 'kr',
  },
  {
    name: 'India',
    alpha2Code: 'IN',
    callingCode: '+91',
    flag: 'https://flagcdn.com/w320/in.png',
    currencyCode: 'INR',
    currencyName: 'Indian rupee',
    currencySymbol: '₹',
  },
  {
    name: 'Indonesia',
    alpha2Code: 'ID',
    callingCode: '+62',
    flag: 'https://flagcdn.com/w320/id.png',
    currencyCode: 'IDR',
    currencyName: 'Indonesian rupiah',
    currencySymbol: 'Rp',
  },
  {
    name: 'Iran',
    alpha2Code: 'IR',
    callingCode: '+98',
    flag: 'https://flagcdn.com/w320/ir.png',
    currencyCode: 'IRR',
    currencyName: 'Iranian rial',
    currencySymbol: '﷼',
  },
  {
    name: 'Iraq',
    alpha2Code: 'IQ',
    callingCode: '+964',
    flag: 'https://flagcdn.com/w320/iq.png',
    currencyCode: 'IQD',
    currencyName: 'Iraqi dinar',
    currencySymbol: 'ع.د',
  },
  {
    name: 'Ireland',
    alpha2Code: 'IE',
    callingCode: '+353',
    flag: 'https://flagcdn.com/w320/ie.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Isle of Man',
    alpha2Code: 'IM',
    callingCode: '+44',
    flag: 'https://flagcdn.com/w320/im.png',
    currencyCode: 'GBP',
    currencyName: 'British pound',
    currencySymbol: '£',
  },
  {
    name: 'Israel',
    alpha2Code: 'IL',
    callingCode: '+972',
    flag: 'https://flagcdn.com/w320/il.png',
    currencyCode: 'ILS',
    currencyName: 'Israeli new shekel',
    currencySymbol: '₪',
  },
  {
    name: 'Italy',
    alpha2Code: 'IT',
    callingCode: '+39',
    flag: 'https://flagcdn.com/w320/it.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Ivory Coast',
    alpha2Code: 'CI',
    callingCode: '+225',
    flag: 'https://flagcdn.com/w320/ci.png',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Jamaica',
    alpha2Code: 'JM',
    callingCode: '+1876',
    flag: 'https://flagcdn.com/w320/jm.png',
    currencyCode: 'JMD',
    currencyName: 'Jamaican dollar',
    currencySymbol: '$',
  },
  {
    name: 'Japan',
    alpha2Code: 'JP',
    callingCode: '+81',
    flag: 'https://flagcdn.com/w320/jp.png',
    currencyCode: 'JPY',
    currencyName: 'Japanese yen',
    currencySymbol: '¥',
  },
  {
    name: 'Jersey',
    alpha2Code: 'JE',
    callingCode: '+44',
    flag: 'https://flagcdn.com/w320/je.png',
    currencyCode: 'GBP',
    currencyName: 'British pound',
    currencySymbol: '£',
  },
  {
    name: 'Jordan',
    alpha2Code: 'JO',
    callingCode: '+962',
    flag: 'https://flagcdn.com/w320/jo.png',
    currencyCode: 'JOD',
    currencyName: 'Jordanian dinar',
    currencySymbol: 'د.ا',
  },
  {
    name: 'Kazakhstan',
    alpha2Code: 'KZ',
    callingCode: '+76',
    flag: 'https://flagcdn.com/w320/kz.png',
    currencyCode: 'KZT',
    currencyName: 'Kazakhstani tenge',
    currencySymbol: '₸',
  },
  {
    name: 'Kenya',
    alpha2Code: 'KE',
    callingCode: '+254',
    flag: 'https://flagcdn.com/w320/ke.png',
    currencyCode: 'KES',
    currencyName: 'Kenyan shilling',
    currencySymbol: 'Sh',
  },
  {
    name: 'Kiribati',
    alpha2Code: 'KI',
    callingCode: '+686',
    flag: 'https://flagcdn.com/w320/ki.png',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Kosovo',
    alpha2Code: 'XK',
    callingCode: '+383',
    flag: 'https://flagcdn.com/w320/xk.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Kuwait',
    alpha2Code: 'KW',
    callingCode: '+965',
    flag: 'https://flagcdn.com/w320/kw.png',
    currencyCode: 'KWD',
    currencyName: 'Kuwaiti dinar',
    currencySymbol: 'د.ك',
  },
  {
    name: 'Kyrgyzstan',
    alpha2Code: 'KG',
    callingCode: '+996',
    flag: 'https://flagcdn.com/w320/kg.png',
    currencyCode: 'KGS',
    currencyName: 'Kyrgyzstani som',
    currencySymbol: 'с',
  },
  {
    name: 'Laos',
    alpha2Code: 'LA',
    callingCode: '+856',
    flag: 'https://flagcdn.com/w320/la.png',
    currencyCode: 'LAK',
    currencyName: 'Lao kip',
    currencySymbol: '₭',
  },
  {
    name: 'Latvia',
    alpha2Code: 'LV',
    callingCode: '+371',
    flag: 'https://flagcdn.com/w320/lv.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Lebanon',
    alpha2Code: 'LB',
    callingCode: '+961',
    flag: 'https://flagcdn.com/w320/lb.png',
    currencyCode: 'LBP',
    currencyName: 'Lebanese pound',
    currencySymbol: 'ل.ل',
  },
  {
    name: 'Lesotho',
    alpha2Code: 'LS',
    callingCode: '+266',
    flag: 'https://flagcdn.com/w320/ls.png',
    currencyCode: 'LSL',
    currencyName: 'Lesotho loti',
    currencySymbol: 'L',
  },
  {
    name: 'Liberia',
    alpha2Code: 'LR',
    callingCode: '+231',
    flag: 'https://flagcdn.com/w320/lr.png',
    currencyCode: 'LRD',
    currencyName: 'Liberian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Libya',
    alpha2Code: 'LY',
    callingCode: '+218',
    flag: 'https://flagcdn.com/w320/ly.png',
    currencyCode: 'LYD',
    currencyName: 'Libyan dinar',
    currencySymbol: 'ل.د',
  },
  {
    name: 'Liechtenstein',
    alpha2Code: 'LI',
    callingCode: '+423',
    flag: 'https://flagcdn.com/w320/li.png',
    currencyCode: 'CHF',
    currencyName: 'Swiss franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Lithuania',
    alpha2Code: 'LT',
    callingCode: '+370',
    flag: 'https://flagcdn.com/w320/lt.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Luxembourg',
    alpha2Code: 'LU',
    callingCode: '+352',
    flag: 'https://flagcdn.com/w320/lu.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Macau',
    alpha2Code: 'MO',
    callingCode: '+853',
    flag: 'https://flagcdn.com/w320/mo.png',
    currencyCode: 'MOP',
    currencyName: 'Macanese pataca',
    currencySymbol: 'P',
  },
  {
    name: 'Madagascar',
    alpha2Code: 'MG',
    callingCode: '+261',
    flag: 'https://flagcdn.com/w320/mg.png',
    currencyCode: 'MGA',
    currencyName: 'Malagasy ariary',
    currencySymbol: 'Ar',
  },
  {
    name: 'Malawi',
    alpha2Code: 'MW',
    callingCode: '+265',
    flag: 'https://flagcdn.com/w320/mw.png',
    currencyCode: 'MWK',
    currencyName: 'Malawian kwacha',
    currencySymbol: 'MK',
  },
  {
    name: 'Malaysia',
    alpha2Code: 'MY',
    callingCode: '+60',
    flag: 'https://flagcdn.com/w320/my.png',
    currencyCode: 'MYR',
    currencyName: 'Malaysian ringgit',
    currencySymbol: 'RM',
  },
  {
    name: 'Maldives',
    alpha2Code: 'MV',
    callingCode: '+960',
    flag: 'https://flagcdn.com/w320/mv.png',
    currencyCode: 'MVR',
    currencyName: 'Maldivian rufiyaa',
    currencySymbol: '.ރ',
  },
  {
    name: 'Mali',
    alpha2Code: 'ML',
    callingCode: '+223',
    flag: 'https://flagcdn.com/w320/ml.png',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Malta',
    alpha2Code: 'MT',
    callingCode: '+356',
    flag: 'https://flagcdn.com/w320/mt.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Marshall Islands',
    alpha2Code: 'MH',
    callingCode: '+692',
    flag: 'https://flagcdn.com/w320/mh.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Martinique',
    alpha2Code: 'MQ',
    callingCode: '+596',
    flag: 'https://flagcdn.com/w320/mq.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Mauritania',
    alpha2Code: 'MR',
    callingCode: '+222',
    flag: 'https://flagcdn.com/w320/mr.png',
    currencyCode: 'MRU',
    currencyName: 'Mauritanian ouguiya',
    currencySymbol: 'UM',
  },
  {
    name: 'Mauritius',
    alpha2Code: 'MU',
    callingCode: '+230',
    flag: 'https://flagcdn.com/w320/mu.png',
    currencyCode: 'MUR',
    currencyName: 'Mauritian rupee',
    currencySymbol: '₨',
  },
  {
    name: 'Mayotte',
    alpha2Code: 'YT',
    callingCode: '+262',
    flag: 'https://flagcdn.com/w320/yt.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Mexico',
    alpha2Code: 'MX',
    callingCode: '+52',
    flag: 'https://flagcdn.com/w320/mx.png',
    currencyCode: 'MXN',
    currencyName: 'Mexican peso',
    currencySymbol: '$',
  },
  {
    name: 'Micronesia',
    alpha2Code: 'FM',
    callingCode: '+691',
    flag: 'https://flagcdn.com/w320/fm.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Moldova',
    alpha2Code: 'MD',
    callingCode: '+373',
    flag: 'https://flagcdn.com/w320/md.png',
    currencyCode: 'MDL',
    currencyName: 'Moldovan leu',
    currencySymbol: 'L',
  },
  {
    name: 'Monaco',
    alpha2Code: 'MC',
    callingCode: '+377',
    flag: 'https://flagcdn.com/w320/mc.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Mongolia',
    alpha2Code: 'MN',
    callingCode: '+976',
    flag: 'https://flagcdn.com/w320/mn.png',
    currencyCode: 'MNT',
    currencyName: 'Mongolian tögrög',
    currencySymbol: '₮',
  },
  {
    name: 'Montenegro',
    alpha2Code: 'ME',
    callingCode: '+382',
    flag: 'https://flagcdn.com/w320/me.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Montserrat',
    alpha2Code: 'MS',
    callingCode: '+1664',
    flag: 'https://flagcdn.com/w320/ms.png',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
  },
  {
    name: 'Morocco',
    alpha2Code: 'MA',
    callingCode: '+212',
    flag: 'https://flagcdn.com/w320/ma.png',
    currencyCode: 'MAD',
    currencyName: 'Moroccan dirham',
    currencySymbol: 'د.م.',
  },
  {
    name: 'Mozambique',
    alpha2Code: 'MZ',
    callingCode: '+258',
    flag: 'https://flagcdn.com/w320/mz.png',
    currencyCode: 'MZN',
    currencyName: 'Mozambican metical',
    currencySymbol: 'MT',
  },
  {
    name: 'Myanmar',
    alpha2Code: 'MM',
    callingCode: '+95',
    flag: 'https://flagcdn.com/w320/mm.png',
    currencyCode: 'MMK',
    currencyName: 'Burmese kyat',
    currencySymbol: 'Ks',
  },
  {
    name: 'Namibia',
    alpha2Code: 'NA',
    callingCode: '+264',
    flag: 'https://flagcdn.com/w320/na.png',
    currencyCode: 'NAD',
    currencyName: 'Namibian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Nauru',
    alpha2Code: 'NR',
    callingCode: '+674',
    flag: 'https://flagcdn.com/w320/nr.png',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Nepal',
    alpha2Code: 'NP',
    callingCode: '+977',
    flag: 'https://flagcdn.com/w320/np.png',
    currencyCode: 'NPR',
    currencyName: 'Nepalese rupee',
    currencySymbol: '₨',
  },
  {
    name: 'Netherlands',
    alpha2Code: 'NL',
    callingCode: '+31',
    flag: 'https://flagcdn.com/w320/nl.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'New Caledonia',
    alpha2Code: 'NC',
    callingCode: '+687',
    flag: 'https://flagcdn.com/w320/nc.png',
    currencyCode: 'XPF',
    currencyName: 'CFP franc',
    currencySymbol: '₣',
  },
  {
    name: 'New Zealand',
    alpha2Code: 'NZ',
    callingCode: '+64',
    flag: 'https://flagcdn.com/w320/nz.png',
    currencyCode: 'NZD',
    currencyName: 'New Zealand dollar',
    currencySymbol: '$',
  },
  {
    name: 'Nicaragua',
    alpha2Code: 'NI',
    callingCode: '+505',
    flag: 'https://flagcdn.com/w320/ni.png',
    currencyCode: 'NIO',
    currencyName: 'Nicaraguan córdoba',
    currencySymbol: 'C$',
  },
  {
    name: 'Niger',
    alpha2Code: 'NE',
    callingCode: '+227',
    flag: 'https://flagcdn.com/w320/ne.png',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Nigeria',
    alpha2Code: 'NG',
    callingCode: '+234',
    flag: 'https://flagcdn.com/w320/ng.png',
    currencyCode: 'NGN',
    currencyName: 'Nigerian naira',
    currencySymbol: '₦',
  },
  {
    name: 'Niue',
    alpha2Code: 'NU',
    callingCode: '+683',
    flag: 'https://flagcdn.com/w320/nu.png',
    currencyCode: 'NZD',
    currencyName: 'New Zealand dollar',
    currencySymbol: '$',
  },
  {
    name: 'Norfolk Island',
    alpha2Code: 'NF',
    callingCode: '+672',
    flag: 'https://flagcdn.com/w320/nf.png',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
  },
  {
    name: 'North Korea',
    alpha2Code: 'KP',
    callingCode: '+850',
    flag: 'https://flagcdn.com/w320/kp.png',
    currencyCode: 'KPW',
    currencyName: 'North Korean won',
    currencySymbol: '₩',
  },
  {
    name: 'North Macedonia',
    alpha2Code: 'MK',
    callingCode: '+389',
    flag: 'https://flagcdn.com/w320/mk.png',
    currencyCode: 'MKD',
    currencyName: 'denar',
    currencySymbol: 'den',
  },
  {
    name: 'Northern Mariana Islands',
    alpha2Code: 'MP',
    callingCode: '+1670',
    flag: 'https://flagcdn.com/w320/mp.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Norway',
    alpha2Code: 'NO',
    callingCode: '+47',
    flag: 'https://flagcdn.com/w320/no.png',
    currencyCode: 'NOK',
    currencyName: 'Norwegian krone',
    currencySymbol: 'kr',
  },
  {
    name: 'Oman',
    alpha2Code: 'OM',
    callingCode: '+968',
    flag: 'https://flagcdn.com/w320/om.png',
    currencyCode: 'OMR',
    currencyName: 'Omani rial',
    currencySymbol: 'ر.ع.',
  },
  {
    name: 'Pakistan',
    alpha2Code: 'PK',
    callingCode: '+92',
    flag: 'https://flagcdn.com/w320/pk.png',
    currencyCode: 'PKR',
    currencyName: 'Pakistani rupee',
    currencySymbol: '₨',
  },
  {
    name: 'Palau',
    alpha2Code: 'PW',
    callingCode: '+680',
    flag: 'https://flagcdn.com/w320/pw.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Palestine',
    alpha2Code: 'PS',
    callingCode: '+970',
    flag: 'https://flagcdn.com/w320/ps.png',
    currencyCode: 'EGP',
    currencyName: 'Egyptian pound',
    currencySymbol: 'E£',
  },
  {
    name: 'Panama',
    alpha2Code: 'PA',
    callingCode: '+507',
    flag: 'https://flagcdn.com/w320/pa.png',
    currencyCode: 'PAB',
    currencyName: 'Panamanian balboa',
    currencySymbol: 'B/.',
  },
  {
    name: 'Papua New Guinea',
    alpha2Code: 'PG',
    callingCode: '+675',
    flag: 'https://flagcdn.com/w320/pg.png',
    currencyCode: 'PGK',
    currencyName: 'Papua New Guinean kina',
    currencySymbol: 'K',
  },
  {
    name: 'Paraguay',
    alpha2Code: 'PY',
    callingCode: '+595',
    flag: 'https://flagcdn.com/w320/py.png',
    currencyCode: 'PYG',
    currencyName: 'Paraguayan guaraní',
    currencySymbol: '₲',
  },
  {
    name: 'Peru',
    alpha2Code: 'PE',
    callingCode: '+51',
    flag: 'https://flagcdn.com/w320/pe.png',
    currencyCode: 'PEN',
    currencyName: 'Peruvian sol',
    currencySymbol: 'S/ ',
  },
  {
    name: 'Philippines',
    alpha2Code: 'PH',
    callingCode: '+63',
    flag: 'https://flagcdn.com/w320/ph.png',
    currencyCode: 'PHP',
    currencyName: 'Philippine peso',
    currencySymbol: '₱',
  },
  {
    name: 'Pitcairn Islands',
    alpha2Code: 'PN',
    callingCode: '+64',
    flag: 'https://flagcdn.com/w320/pn.png',
    currencyCode: 'NZD',
    currencyName: 'New Zealand dollar',
    currencySymbol: '$',
  },
  {
    name: 'Poland',
    alpha2Code: 'PL',
    callingCode: '+48',
    flag: 'https://flagcdn.com/w320/pl.png',
    currencyCode: 'PLN',
    currencyName: 'Polish złoty',
    currencySymbol: 'zł',
  },
  {
    name: 'Portugal',
    alpha2Code: 'PT',
    callingCode: '+351',
    flag: 'https://flagcdn.com/w320/pt.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Puerto Rico',
    alpha2Code: 'PR',
    callingCode: '+1787',
    flag: 'https://flagcdn.com/w320/pr.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Qatar',
    alpha2Code: 'QA',
    callingCode: '+974',
    flag: 'https://flagcdn.com/w320/qa.png',
    currencyCode: 'QAR',
    currencyName: 'Qatari riyal',
    currencySymbol: 'ر.ق',
  },
  {
    name: 'Republic of the Congo',
    alpha2Code: 'CG',
    callingCode: '+242',
    flag: 'https://flagcdn.com/w320/cg.png',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Réunion',
    alpha2Code: 'RE',
    callingCode: '+262',
    flag: 'https://flagcdn.com/w320/re.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Romania',
    alpha2Code: 'RO',
    callingCode: '+40',
    flag: 'https://flagcdn.com/w320/ro.png',
    currencyCode: 'RON',
    currencyName: 'Romanian leu',
    currencySymbol: 'lei',
  },
  {
    name: 'Russia',
    alpha2Code: 'RU',
    callingCode: '+73',
    flag: 'https://flagcdn.com/w320/ru.png',
    currencyCode: 'RUB',
    currencyName: 'Russian ruble',
    currencySymbol: '₽',
  },
  {
    name: 'Rwanda',
    alpha2Code: 'RW',
    callingCode: '+250',
    flag: 'https://flagcdn.com/w320/rw.png',
    currencyCode: 'RWF',
    currencyName: 'Rwandan franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Saint Barthélemy',
    alpha2Code: 'BL',
    callingCode: '+590',
    flag: 'https://flagcdn.com/w320/bl.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2Code: 'SH',
    callingCode: '+290',
    flag: 'https://flagcdn.com/w320/sh.png',
    currencyCode: 'GBP',
    currencyName: 'Pound sterling',
    currencySymbol: '£',
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2Code: 'KN',
    callingCode: '+1869',
    flag: 'https://flagcdn.com/w320/kn.png',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
  },
  {
    name: 'Saint Lucia',
    alpha2Code: 'LC',
    callingCode: '+1758',
    flag: 'https://flagcdn.com/w320/lc.png',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
  },
  {
    name: 'Saint Martin',
    alpha2Code: 'MF',
    callingCode: '+590',
    flag: 'https://flagcdn.com/w320/mf.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2Code: 'PM',
    callingCode: '+508',
    flag: 'https://flagcdn.com/w320/pm.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2Code: 'VC',
    callingCode: '+1784',
    flag: 'https://flagcdn.com/w320/vc.png',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
  },
  {
    name: 'Samoa',
    alpha2Code: 'WS',
    callingCode: '+685',
    flag: 'https://flagcdn.com/w320/ws.png',
    currencyCode: 'WST',
    currencyName: 'Samoan tālā',
    currencySymbol: 'T',
  },
  {
    name: 'San Marino',
    alpha2Code: 'SM',
    callingCode: '+378',
    flag: 'https://flagcdn.com/w320/sm.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'São Tomé and Príncipe',
    alpha2Code: 'ST',
    callingCode: '+239',
    flag: 'https://flagcdn.com/w320/st.png',
    currencyCode: 'STN',
    currencyName: 'São Tomé and Príncipe dobra',
    currencySymbol: 'Db',
  },
  {
    name: 'Saudi Arabia',
    alpha2Code: 'SA',
    callingCode: '+966',
    flag: 'https://flagcdn.com/w320/sa.png',
    currencyCode: 'SAR',
    currencyName: 'Saudi riyal',
    currencySymbol: 'ر.س',
  },
  {
    name: 'Senegal',
    alpha2Code: 'SN',
    callingCode: '+221',
    flag: 'https://flagcdn.com/w320/sn.png',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Serbia',
    alpha2Code: 'RS',
    callingCode: '+381',
    flag: 'https://flagcdn.com/w320/rs.png',
    currencyCode: 'RSD',
    currencyName: 'Serbian dinar',
    currencySymbol: 'дин.',
  },
  {
    name: 'Seychelles',
    alpha2Code: 'SC',
    callingCode: '+248',
    flag: 'https://flagcdn.com/w320/sc.png',
    currencyCode: 'SCR',
    currencyName: 'Seychellois rupee',
    currencySymbol: '₨',
  },
  {
    name: 'Sierra Leone',
    alpha2Code: 'SL',
    callingCode: '+232',
    flag: 'https://flagcdn.com/w320/sl.png',
    currencyCode: 'SLL',
    currencyName: 'Sierra Leonean leone',
    currencySymbol: 'Le',
  },
  {
    name: 'Singapore',
    alpha2Code: 'SG',
    callingCode: '+65',
    flag: 'https://flagcdn.com/w320/sg.png',
    currencyCode: 'SGD',
    currencyName: 'Singapore dollar',
    currencySymbol: '$',
  },
  {
    name: 'Sint Maarten',
    alpha2Code: 'SX',
    callingCode: '+1721',
    flag: 'https://flagcdn.com/w320/sx.png',
    currencyCode: 'ANG',
    currencyName: 'Netherlands Antillean guilder',
    currencySymbol: 'ƒ',
  },
  {
    name: 'Slovakia',
    alpha2Code: 'SK',
    callingCode: '+421',
    flag: 'https://flagcdn.com/w320/sk.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Slovenia',
    alpha2Code: 'SI',
    callingCode: '+386',
    flag: 'https://flagcdn.com/w320/si.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Solomon Islands',
    alpha2Code: 'SB',
    callingCode: '+677',
    flag: 'https://flagcdn.com/w320/sb.png',
    currencyCode: 'SBD',
    currencyName: 'Solomon Islands dollar',
    currencySymbol: '$',
  },
  {
    name: 'Somalia',
    alpha2Code: 'SO',
    callingCode: '+252',
    flag: 'https://flagcdn.com/w320/so.png',
    currencyCode: 'SOS',
    currencyName: 'Somali shilling',
    currencySymbol: 'Sh',
  },
  {
    name: 'South Africa',
    alpha2Code: 'ZA',
    callingCode: '+27',
    flag: 'https://flagcdn.com/w320/za.png',
    currencyCode: 'ZAR',
    currencyName: 'South African rand',
    currencySymbol: 'R',
  },
  {
    name: 'South Georgia',
    alpha2Code: 'GS',
    callingCode: '+500',
    flag: 'https://flagcdn.com/w320/gs.png',
    currencyCode: 'SHP',
    currencyName: 'Saint Helena pound',
    currencySymbol: '£',
  },
  {
    name: 'South Korea',
    alpha2Code: 'KR',
    callingCode: '+82',
    flag: 'https://flagcdn.com/w320/kr.png',
    currencyCode: 'KRW',
    currencyName: 'South Korean won',
    currencySymbol: '₩',
  },
  {
    name: 'South Sudan',
    alpha2Code: 'SS',
    callingCode: '+211',
    flag: 'https://flagcdn.com/w320/ss.png',
    currencyCode: 'SSP',
    currencyName: 'South Sudanese pound',
    currencySymbol: '£',
  },
  {
    name: 'Spain',
    alpha2Code: 'ES',
    callingCode: '+34',
    flag: 'https://flagcdn.com/w320/es.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Sri Lanka',
    alpha2Code: 'LK',
    callingCode: '+94',
    flag: 'https://flagcdn.com/w320/lk.png',
    currencyCode: 'LKR',
    currencyName: 'Sri Lankan rupee',
    currencySymbol: 'Rs  රු',
  },
  {
    name: 'Sudan',
    alpha2Code: 'SD',
    callingCode: '+249',
    flag: 'https://flagcdn.com/w320/sd.png',
    currencyCode: 'SDG',
    currencyName: 'Sudanese pound',
    currencySymbol: '',
  },
  {
    name: 'Suriname',
    alpha2Code: 'SR',
    callingCode: '+597',
    flag: 'https://flagcdn.com/w320/sr.png',
    currencyCode: 'SRD',
    currencyName: 'Surinamese dollar',
    currencySymbol: '$',
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2Code: 'SJ',
    callingCode: '+4779',
    flag: 'https://flagcdn.com/w320/sj.png',
    currencyCode: 'NOK',
    currencyName: 'krone',
    currencySymbol: 'kr',
  },
  {
    name: 'Sweden',
    alpha2Code: 'SE',
    callingCode: '+46',
    flag: 'https://flagcdn.com/w320/se.png',
    currencyCode: 'SEK',
    currencyName: 'Swedish krona',
    currencySymbol: 'kr',
  },
  {
    name: 'Switzerland',
    alpha2Code: 'CH',
    callingCode: '+41',
    flag: 'https://flagcdn.com/w320/ch.png',
    currencyCode: 'CHF',
    currencyName: 'Swiss franc',
    currencySymbol: 'Fr.',
  },
  {
    name: 'Syria',
    alpha2Code: 'SY',
    callingCode: '+963',
    flag: 'https://flagcdn.com/w320/sy.png',
    currencyCode: 'SYP',
    currencyName: 'Syrian pound',
    currencySymbol: '£',
  },
  {
    name: 'Taiwan',
    alpha2Code: 'TW',
    callingCode: '+886',
    flag: 'https://flagcdn.com/w320/tw.png',
    currencyCode: 'TWD',
    currencyName: 'New Taiwan dollar',
    currencySymbol: '$',
  },
  {
    name: 'Tajikistan',
    alpha2Code: 'TJ',
    callingCode: '+992',
    flag: 'https://flagcdn.com/w320/tj.png',
    currencyCode: 'TJS',
    currencyName: 'Tajikistani somoni',
    currencySymbol: 'ЅМ',
  },
  {
    name: 'Tanzania',
    alpha2Code: 'TZ',
    callingCode: '+255',
    flag: 'https://flagcdn.com/w320/tz.png',
    currencyCode: 'TZS',
    currencyName: 'Tanzanian shilling',
    currencySymbol: 'Sh',
  },
  {
    name: 'Thailand',
    alpha2Code: 'TH',
    callingCode: '+66',
    flag: 'https://flagcdn.com/w320/th.png',
    currencyCode: 'THB',
    currencyName: 'Thai baht',
    currencySymbol: '฿',
  },
  {
    name: 'Timor-Leste',
    alpha2Code: 'TL',
    callingCode: '+670',
    flag: 'https://flagcdn.com/w320/tl.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Togo',
    alpha2Code: 'TG',
    callingCode: '+228',
    flag: 'https://flagcdn.com/w320/tg.png',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
  },
  {
    name: 'Tokelau',
    alpha2Code: 'TK',
    callingCode: '+690',
    flag: 'https://flagcdn.com/w320/tk.png',
    currencyCode: 'NZD',
    currencyName: 'New Zealand dollar',
    currencySymbol: '$',
  },
  {
    name: 'Tonga',
    alpha2Code: 'TO',
    callingCode: '+676',
    flag: 'https://flagcdn.com/w320/to.png',
    currencyCode: 'TOP',
    currencyName: 'Tongan paʻanga',
    currencySymbol: 'T$',
  },
  {
    name: 'Trinidad and Tobago',
    alpha2Code: 'TT',
    callingCode: '+1868',
    flag: 'https://flagcdn.com/w320/tt.png',
    currencyCode: 'TTD',
    currencyName: 'Trinidad and Tobago dollar',
    currencySymbol: '$',
  },
  {
    name: 'Tunisia',
    alpha2Code: 'TN',
    callingCode: '+216',
    flag: 'https://flagcdn.com/w320/tn.png',
    currencyCode: 'TND',
    currencyName: 'Tunisian dinar',
    currencySymbol: 'د.ت',
  },
  {
    name: 'Turkey',
    alpha2Code: 'TR',
    callingCode: '+90',
    flag: 'https://flagcdn.com/w320/tr.png',
    currencyCode: 'TRY',
    currencyName: 'Turkish lira',
    currencySymbol: '₺',
  },
  {
    name: 'Turkmenistan',
    alpha2Code: 'TM',
    callingCode: '+993',
    flag: 'https://flagcdn.com/w320/tm.png',
    currencyCode: 'TMT',
    currencyName: 'Turkmenistan manat',
    currencySymbol: 'm',
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2Code: 'TC',
    callingCode: '+1649',
    flag: 'https://flagcdn.com/w320/tc.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Tuvalu',
    alpha2Code: 'TV',
    callingCode: '+688',
    flag: 'https://flagcdn.com/w320/tv.png',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
  },
  {
    name: 'Uganda',
    alpha2Code: 'UG',
    callingCode: '+256',
    flag: 'https://flagcdn.com/w320/ug.png',
    currencyCode: 'UGX',
    currencyName: 'Ugandan shilling',
    currencySymbol: 'Sh',
  },
  {
    name: 'Ukraine',
    alpha2Code: 'UA',
    callingCode: '+380',
    flag: 'https://flagcdn.com/w320/ua.png',
    currencyCode: 'UAH',
    currencyName: 'Ukrainian hryvnia',
    currencySymbol: '₴',
  },
  {
    name: 'United Arab Emirates',
    alpha2Code: 'AE',
    callingCode: '+971',
    flag: 'https://flagcdn.com/w320/ae.png',
    currencyCode: 'AED',
    currencyName: 'United Arab Emirates dirham',
    currencySymbol: 'د.إ',
  },
  {
    name: 'United Kingdom',
    alpha2Code: 'GB',
    callingCode: '+44',
    flag: 'https://flagcdn.com/w320/gb.png',
    currencyCode: 'GBP',
    currencyName: 'British pound',
    currencySymbol: '£',
  },
  {
    name: 'United States',
    alpha2Code: 'US',
    callingCode: '+1201',
    flag: 'https://flagcdn.com/w320/us.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2Code: 'UM',
    callingCode: '+268',
    flag: 'https://flagcdn.com/w320/um.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'United States Virgin Islands',
    alpha2Code: 'VI',
    callingCode: '+1340',
    flag: 'https://flagcdn.com/w320/vi.png',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
  },
  {
    name: 'Uruguay',
    alpha2Code: 'UY',
    callingCode: '+598',
    flag: 'https://flagcdn.com/w320/uy.png',
    currencyCode: 'UYU',
    currencyName: 'Uruguayan peso',
    currencySymbol: '$',
  },
  {
    name: 'Uzbekistan',
    alpha2Code: 'UZ',
    callingCode: '+998',
    flag: 'https://flagcdn.com/w320/uz.png',
    currencyCode: 'UZS',
    currencyName: 'Uzbekistani soʻm',
    currencySymbol: "so'm",
  },
  {
    name: 'Vanuatu',
    alpha2Code: 'VU',
    callingCode: '+678',
    flag: 'https://flagcdn.com/w320/vu.png',
    currencyCode: 'VUV',
    currencyName: 'Vanuatu vatu',
    currencySymbol: 'Vt',
  },
  {
    name: 'Vatican City',
    alpha2Code: 'VA',
    callingCode: '+3906698',
    flag: 'https://flagcdn.com/w320/va.png',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
  },
  {
    name: 'Venezuela',
    alpha2Code: 'VE',
    callingCode: '+58',
    flag: 'https://flagcdn.com/w320/ve.png',
    currencyCode: 'VES',
    currencyName: 'Venezuelan bolívar soberano',
    currencySymbol: 'Bs.S.',
  },
  {
    name: 'Vietnam',
    alpha2Code: 'VN',
    callingCode: '+84',
    flag: 'https://flagcdn.com/w320/vn.png',
    currencyCode: 'VND',
    currencyName: 'Vietnamese đồng',
    currencySymbol: '₫',
  },
  {
    name: 'Wallis and Futuna',
    alpha2Code: 'WF',
    callingCode: '+681',
    flag: 'https://flagcdn.com/w320/wf.png',
    currencyCode: 'XPF',
    currencyName: 'CFP franc',
    currencySymbol: '₣',
  },
  {
    name: 'Western Sahara',
    alpha2Code: 'EH',
    callingCode: '+2125288',
    flag: 'https://flagcdn.com/w320/eh.png',
    currencyCode: 'DZD',
    currencyName: 'Algerian dinar',
    currencySymbol: 'دج',
  },
  {
    name: 'Yemen',
    alpha2Code: 'YE',
    callingCode: '+967',
    flag: 'https://flagcdn.com/w320/ye.png',
    currencyCode: 'YER',
    currencyName: 'Yemeni rial',
    currencySymbol: '﷼',
  },
  {
    name: 'Zambia',
    alpha2Code: 'ZM',
    callingCode: '+260',
    flag: 'https://flagcdn.com/w320/zm.png',
    currencyCode: 'ZMW',
    currencyName: 'Zambian kwacha',
    currencySymbol: 'ZK',
  },
  {
    name: 'Zimbabwe',
    alpha2Code: 'ZW',
    callingCode: '+263',
    flag: 'https://flagcdn.com/w320/zw.png',
    currencyCode: 'ZWL',
    currencyName: 'Zimbabwean dollar',
    currencySymbol: '$',
  },
];
