export const countriesData = [
  {
    name: 'Afghanistan',
    alpha2Code: 'AF',
    callingCode: '+93',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png',
  },
  {
    name: 'Åland Islands',
    alpha2Code: 'AX',
    callingCode: '+35818',
    flag: 'https://flagcdn.com/w320/ax.png',
  },
  {
    name: 'Albania',
    alpha2Code: 'AL',
    callingCode: '+355',
    flag: 'https://flagcdn.com/w320/al.png',
  },
  {
    name: 'Algeria',
    alpha2Code: 'DZ',
    callingCode: '+213',
    flag: 'https://flagcdn.com/w320/dz.png',
  },
  {
    name: 'American Samoa',
    alpha2Code: 'AS',
    callingCode: '+1684',
    flag: 'https://flagcdn.com/w320/as.png',
  },
  {
    name: 'Andorra',
    alpha2Code: 'AD',
    callingCode: '+376',
    flag: 'https://flagcdn.com/w320/ad.png',
  },
  {
    name: 'Angola',
    alpha2Code: 'AO',
    callingCode: '+244',
    flag: 'https://flagcdn.com/w320/ao.png',
  },
  {
    name: 'Anguilla',
    alpha2Code: 'AI',
    callingCode: '+1264',
    flag: 'https://flagcdn.com/w320/ai.png',
  },
  // {
  //   name: 'Antarctica',
  //   alpha2Code: 'AQ',
  //   callingCode: '',
  //   flag: 'https://flagcdn.com/w320/aq.png',
  // },
  {
    name: 'Antigua and Barbuda',
    alpha2Code: 'AG',
    callingCode: '+1268',
    flag: 'https://flagcdn.com/w320/ag.png',
  },
  {
    name: 'Argentina',
    alpha2Code: 'AR',
    callingCode: '+54',
    flag: 'https://flagcdn.com/w320/ar.png',
  },
  {
    name: 'Armenia',
    alpha2Code: 'AM',
    callingCode: '+374',
    flag: 'https://flagcdn.com/w320/am.png',
  },
  {
    name: 'Aruba',
    alpha2Code: 'AW',
    callingCode: '+297',
    flag: 'https://flagcdn.com/w320/aw.png',
  },
  {
    name: 'Australia',
    alpha2Code: 'AU',
    callingCode: '+61',
    flag: 'https://flagcdn.com/w320/au.png',
  },
  {
    name: 'Austria',
    alpha2Code: 'AT',
    callingCode: '+43',
    flag: 'https://flagcdn.com/w320/at.png',
  },
  {
    name: 'Azerbaijan',
    alpha2Code: 'AZ',
    callingCode: '+994',
    flag: 'https://flagcdn.com/w320/az.png',
  },
  {
    name: 'Bahamas',
    alpha2Code: 'BS',
    callingCode: '+1242',
    flag: 'https://flagcdn.com/w320/bs.png',
  },
  {
    name: 'Bahrain',
    alpha2Code: 'BH',
    callingCode: '+973',
    flag: 'https://flagcdn.com/w320/bh.png',
  },
  {
    name: 'Bangladesh',
    alpha2Code: 'BD',
    callingCode: '+880',
    flag: 'https://flagcdn.com/w320/bd.png',
  },
  {
    name: 'Barbados',
    alpha2Code: 'BB',
    callingCode: '+1246',
    flag: 'https://flagcdn.com/w320/bb.png',
  },
  {
    name: 'Belarus',
    alpha2Code: 'BY',
    callingCode: '+375',
    flag: 'https://flagcdn.com/w320/by.png',
  },
  {
    name: 'Belgium',
    alpha2Code: 'BE',
    callingCode: '+32',
    flag: 'https://flagcdn.com/w320/be.png',
  },
  {
    name: 'Belize',
    alpha2Code: 'BZ',
    callingCode: '+501',
    flag: 'https://flagcdn.com/w320/bz.png',
  },
  {
    name: 'Benin',
    alpha2Code: 'BJ',
    callingCode: '+229',
    flag: 'https://flagcdn.com/w320/bj.png',
  },
  {
    name: 'Bermuda',
    alpha2Code: 'BM',
    callingCode: '+1441',
    flag: 'https://flagcdn.com/w320/bm.png',
  },
  {
    name: 'Bhutan',
    alpha2Code: 'BT',
    callingCode: '+975',
    flag: 'https://flagcdn.com/w320/bt.png',
  },
  {
    name: 'Bolivia',
    alpha2Code: 'BO',
    callingCode: '+591',
    flag: 'https://flagcdn.com/w320/bo.png',
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2Code: 'BA',
    callingCode: '+387',
    flag: 'https://flagcdn.com/w320/ba.png',
  },
  {
    name: 'Botswana',
    alpha2Code: 'BW',
    callingCode: '+267',
    flag: 'https://flagcdn.com/w320/bw.png',
  },
  {
    name: 'Bouvet Island',
    alpha2Code: 'BV',
    callingCode: '+47',
    flag: 'https://flagcdn.com/w320/bv.png',
  },
  {
    name: 'Brazil',
    alpha2Code: 'BR',
    callingCode: '+55',
    flag: 'https://flagcdn.com/w320/br.png',
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2Code: 'IO',
    callingCode: '+246',
    flag: 'https://flagcdn.com/w320/io.png',
  },
  {
    name: 'British Virgin Islands',
    alpha2Code: 'VG',
    callingCode: '+1284',
    flag: 'https://flagcdn.com/w320/vg.png',
  },
  {
    name: 'Brunei',
    alpha2Code: 'BN',
    callingCode: '+673',
    flag: 'https://flagcdn.com/w320/bn.png',
  },
  {
    name: 'Bulgaria',
    alpha2Code: 'BG',
    callingCode: '+359',
    flag: 'https://flagcdn.com/w320/bg.png',
  },
  {
    name: 'Burkina Faso',
    alpha2Code: 'BF',
    callingCode: '+226',
    flag: 'https://flagcdn.com/w320/bf.png',
  },
  {
    name: 'Burundi',
    alpha2Code: 'BI',
    callingCode: '+257',
    flag: 'https://flagcdn.com/w320/bi.png',
  },
  {
    name: 'Cambodia',
    alpha2Code: 'KH',
    callingCode: '+855',
    flag: 'https://flagcdn.com/w320/kh.png',
  },
  {
    name: 'Cameroon',
    alpha2Code: 'CM',
    callingCode: '+237',
    flag: 'https://flagcdn.com/w320/cm.png',
  },
  {
    name: 'Canada',
    alpha2Code: 'CA',
    callingCode: '+1',
    flag: 'https://flagcdn.com/w320/ca.png',
  },
  {
    name: 'Cape Verde',
    alpha2Code: 'CV',
    callingCode: '+238',
    flag: 'https://flagcdn.com/w320/cv.png',
  },
  {
    name: 'Caribbean Netherlands',
    alpha2Code: 'BQ',
    callingCode: '+599',
    flag: 'https://flagcdn.com/w320/bq.png',
  },
  {
    name: 'Cayman Islands',
    alpha2Code: 'KY',
    callingCode: '+1345',
    flag: 'https://flagcdn.com/w320/ky.png',
  },
  {
    name: 'Central African Republic',
    alpha2Code: 'CF',
    callingCode: '+236',
    flag: 'https://flagcdn.com/w320/cf.png',
  },
  {
    name: 'Chad',
    alpha2Code: 'TD',
    callingCode: '+235',
    flag: 'https://flagcdn.com/w320/td.png',
  },
  {
    name: 'Chile',
    alpha2Code: 'CL',
    callingCode: '+56',
    flag: 'https://flagcdn.com/w320/cl.png',
  },
  {
    name: 'China',
    alpha2Code: 'CN',
    callingCode: '+86',
    flag: 'https://flagcdn.com/w320/cn.png',
  },
  {
    name: 'Christmas Island',
    alpha2Code: 'CX',
    callingCode: '+61',
    flag: 'https://flagcdn.com/w320/cx.png',
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2Code: 'CC',
    callingCode: '+61',
    flag: 'https://flagcdn.com/w320/cc.png',
  },
  {
    name: 'Colombia',
    alpha2Code: 'CO',
    callingCode: '+57',
    flag: 'https://flagcdn.com/w320/co.png',
  },
  {
    name: 'Comoros',
    alpha2Code: 'KM',
    callingCode: '+269',
    flag: 'https://flagcdn.com/w320/km.png',
  },
  {
    name: 'Cook Islands',
    alpha2Code: 'CK',
    callingCode: '+682',
    flag: 'https://flagcdn.com/w320/ck.png',
  },
  {
    name: 'Costa Rica',
    alpha2Code: 'CR',
    callingCode: '+506',
    flag: 'https://flagcdn.com/w320/cr.png',
  },
  {
    name: 'Croatia',
    alpha2Code: 'HR',
    callingCode: '+385',
    flag: 'https://flagcdn.com/w320/hr.png',
  },
  {
    name: 'Cuba',
    alpha2Code: 'CU',
    callingCode: '+53',
    flag: 'https://flagcdn.com/w320/cu.png',
  },
  {
    name: 'Curaçao',
    alpha2Code: 'CW',
    callingCode: '+599',
    flag: 'https://flagcdn.com/w320/cw.png',
  },
  {
    name: 'Cyprus',
    alpha2Code: 'CY',
    callingCode: '+357',
    flag: 'https://flagcdn.com/w320/cy.png',
  },
  {
    name: 'Czechia',
    alpha2Code: 'CZ',
    callingCode: '+420',
    flag: 'https://flagcdn.com/w320/cz.png',
  },
  {
    name: 'Denmark',
    alpha2Code: 'DK',
    callingCode: '+45',
    flag: 'https://flagcdn.com/w320/dk.png',
  },
  {
    name: 'Djibouti',
    alpha2Code: 'DJ',
    callingCode: '+253',
    flag: 'https://flagcdn.com/w320/dj.png',
  },
  {
    name: 'Dominica',
    alpha2Code: 'DM',
    callingCode: '+1767',
    flag: 'https://flagcdn.com/w320/dm.png',
  },
  {
    name: 'Dominican Republic',
    alpha2Code: 'DO',
    callingCode: '+1809',
    flag: 'https://flagcdn.com/w320/do.png',
  },
  {
    name: 'DR Congo',
    alpha2Code: 'CD',
    callingCode: '+243',
    flag: 'https://flagcdn.com/w320/cd.png',
  },
  {
    name: 'Ecuador',
    alpha2Code: 'EC',
    callingCode: '+593',
    flag: 'https://flagcdn.com/w320/ec.png',
  },
  {
    name: 'Egypt',
    alpha2Code: 'EG',
    callingCode: '+20',
    flag: 'https://flagcdn.com/w320/eg.png',
  },
  {
    name: 'El Salvador',
    alpha2Code: 'SV',
    callingCode: '+503',
    flag: 'https://flagcdn.com/w320/sv.png',
  },
  {
    name: 'Equatorial Guinea',
    alpha2Code: 'GQ',
    callingCode: '+240',
    flag: 'https://flagcdn.com/w320/gq.png',
  },
  {
    name: 'Eritrea',
    alpha2Code: 'ER',
    callingCode: '+291',
    flag: 'https://flagcdn.com/w320/er.png',
  },
  {
    name: 'Estonia',
    alpha2Code: 'EE',
    callingCode: '+372',
    flag: 'https://flagcdn.com/w320/ee.png',
  },
  {
    name: 'Eswatini',
    alpha2Code: 'SZ',
    callingCode: '+268',
    flag: 'https://flagcdn.com/w320/sz.png',
  },
  {
    name: 'Ethiopia',
    alpha2Code: 'ET',
    callingCode: '+251',
    flag: 'https://flagcdn.com/w320/et.png',
  },
  {
    name: 'Falkland Islands',
    alpha2Code: 'FK',
    callingCode: '+500',
    flag: 'https://flagcdn.com/w320/fk.png',
  },
  {
    name: 'Faroe Islands',
    alpha2Code: 'FO',
    callingCode: '+298',
    flag: 'https://flagcdn.com/w320/fo.png',
  },
  {
    name: 'Fiji',
    alpha2Code: 'FJ',
    callingCode: '+679',
    flag: 'https://flagcdn.com/w320/fj.png',
  },
  {
    name: 'Finland',
    alpha2Code: 'FI',
    callingCode: '+358',
    flag: 'https://flagcdn.com/w320/fi.png',
  },
  {
    name: 'France',
    alpha2Code: 'FR',
    callingCode: '+33',
    flag: 'https://flagcdn.com/w320/fr.png',
  },
  {
    name: 'French Guiana',
    alpha2Code: 'GF',
    callingCode: '+594',
    flag: 'https://flagcdn.com/w320/gf.png',
  },
  {
    name: 'French Polynesia',
    alpha2Code: 'PF',
    callingCode: '+689',
    flag: 'https://flagcdn.com/w320/pf.png',
  },
  {
    name: 'French Southern and Antarctic Lands',
    alpha2Code: 'TF',
    callingCode: '+262',
    flag: 'https://flagcdn.com/w320/tf.png',
  },
  {
    name: 'Gabon',
    alpha2Code: 'GA',
    callingCode: '+241',
    flag: 'https://flagcdn.com/w320/ga.png',
  },
  {
    name: 'Gambia',
    alpha2Code: 'GM',
    callingCode: '+220',
    flag: 'https://flagcdn.com/w320/gm.png',
  },
  {
    name: 'Georgia',
    alpha2Code: 'GE',
    callingCode: '+995',
    flag: 'https://flagcdn.com/w320/ge.png',
  },
  {
    name: 'Germany',
    alpha2Code: 'DE',
    callingCode: '+49',
    flag: 'https://flagcdn.com/w320/de.png',
  },
  {
    name: 'Ghana',
    alpha2Code: 'GH',
    callingCode: '+233',
    flag: 'https://flagcdn.com/w320/gh.png',
  },
  {
    name: 'Gibraltar',
    alpha2Code: 'GI',
    callingCode: '+350',
    flag: 'https://flagcdn.com/w320/gi.png',
  },
  {
    name: 'Greece',
    alpha2Code: 'GR',
    callingCode: '+30',
    flag: 'https://flagcdn.com/w320/gr.png',
  },
  {
    name: 'Greenland',
    alpha2Code: 'GL',
    callingCode: '+299',
    flag: 'https://flagcdn.com/w320/gl.png',
  },
  {
    name: 'Grenada',
    alpha2Code: 'GD',
    callingCode: '+1473',
    flag: 'https://flagcdn.com/w320/gd.png',
  },
  {
    name: 'Guadeloupe',
    alpha2Code: 'GP',
    callingCode: '+590',
    flag: 'https://flagcdn.com/w320/gp.png',
  },
  {
    name: 'Guam',
    alpha2Code: 'GU',
    callingCode: '+1671',
    flag: 'https://flagcdn.com/w320/gu.png',
  },
  {
    name: 'Guatemala',
    alpha2Code: 'GT',
    callingCode: '+502',
    flag: 'https://flagcdn.com/w320/gt.png',
  },
  {
    name: 'Guernsey',
    alpha2Code: 'GG',
    callingCode: '+44',
    flag: 'https://flagcdn.com/w320/gg.png',
  },
  {
    name: 'Guinea',
    alpha2Code: 'GN',
    callingCode: '+224',
    flag: 'https://flagcdn.com/w320/gn.png',
  },
  {
    name: 'Guinea-Bissau',
    alpha2Code: 'GW',
    callingCode: '+245',
    flag: 'https://flagcdn.com/w320/gw.png',
  },
  {
    name: 'Guyana',
    alpha2Code: 'GY',
    callingCode: '+592',
    flag: 'https://flagcdn.com/w320/gy.png',
  },
  {
    name: 'Haiti',
    alpha2Code: 'HT',
    callingCode: '+509',
    flag: 'https://flagcdn.com/w320/ht.png',
  },
  {
    name: 'Heard Island and McDonald Islands',
    alpha2Code: 'HM',
    callingCode: '',
    flag: 'https://flagcdn.com/w320/hm.png',
  },
  {
    name: 'Honduras',
    alpha2Code: 'HN',
    callingCode: '+504',
    flag: 'https://flagcdn.com/w320/hn.png',
  },
  {
    name: 'Hong Kong',
    alpha2Code: 'HK',
    callingCode: '+852',
    flag: 'https://flagcdn.com/w320/hk.png',
  },
  {
    name: 'Hungary',
    alpha2Code: 'HU',
    callingCode: '+36',
    flag: 'https://flagcdn.com/w320/hu.png',
  },
  {
    name: 'Iceland',
    alpha2Code: 'IS',
    callingCode: '+354',
    flag: 'https://flagcdn.com/w320/is.png',
  },
  {
    name: 'India',
    alpha2Code: 'IN',
    callingCode: '+91',
    flag: 'https://flagcdn.com/w320/in.png',
  },
  {
    name: 'Indonesia',
    alpha2Code: 'ID',
    callingCode: '+62',
    flag: 'https://flagcdn.com/w320/id.png',
  },
  {
    name: 'Iran',
    alpha2Code: 'IR',
    callingCode: '+98',
    flag: 'https://flagcdn.com/w320/ir.png',
  },
  {
    name: 'Iraq',
    alpha2Code: 'IQ',
    callingCode: '+964',
    flag: 'https://flagcdn.com/w320/iq.png',
  },
  {
    name: 'Ireland',
    alpha2Code: 'IE',
    callingCode: '+353',
    flag: 'https://flagcdn.com/w320/ie.png',
  },
  {
    name: 'Isle of Man',
    alpha2Code: 'IM',
    callingCode: '+44',
    flag: 'https://flagcdn.com/w320/im.png',
  },
  {
    name: 'Israel',
    alpha2Code: 'IL',
    callingCode: '+972',
    flag: 'https://flagcdn.com/w320/il.png',
  },
  {
    name: 'Italy',
    alpha2Code: 'IT',
    callingCode: '+39',
    flag: 'https://flagcdn.com/w320/it.png',
  },
  {
    name: 'Ivory Coast',
    alpha2Code: 'CI',
    callingCode: '+225',
    flag: 'https://flagcdn.com/w320/ci.png',
  },
  {
    name: 'Jamaica',
    alpha2Code: 'JM',
    callingCode: '+1876',
    flag: 'https://flagcdn.com/w320/jm.png',
  },
  {
    name: 'Japan',
    alpha2Code: 'JP',
    callingCode: '+81',
    flag: 'https://flagcdn.com/w320/jp.png',
  },
  {
    name: 'Jersey',
    alpha2Code: 'JE',
    callingCode: '+44',
    flag: 'https://flagcdn.com/w320/je.png',
  },
  {
    name: 'Jordan',
    alpha2Code: 'JO',
    callingCode: '+962',
    flag: 'https://flagcdn.com/w320/jo.png',
  },
  {
    name: 'Kazakhstan',
    alpha2Code: 'KZ',
    callingCode: '+76',
    flag: 'https://flagcdn.com/w320/kz.png',
  },
  {
    name: 'Kenya',
    alpha2Code: 'KE',
    callingCode: '+254',
    flag: 'https://flagcdn.com/w320/ke.png',
  },
  {
    name: 'Kiribati',
    alpha2Code: 'KI',
    callingCode: '+686',
    flag: 'https://flagcdn.com/w320/ki.png',
  },
  {
    name: 'Kosovo',
    alpha2Code: 'XK',
    callingCode: '+383',
    flag: 'https://flagcdn.com/w320/xk.png',
  },
  {
    name: 'Kuwait',
    alpha2Code: 'KW',
    callingCode: '+965',
    flag: 'https://flagcdn.com/w320/kw.png',
  },
  {
    name: 'Kyrgyzstan',
    alpha2Code: 'KG',
    callingCode: '+996',
    flag: 'https://flagcdn.com/w320/kg.png',
  },
  {
    name: 'Laos',
    alpha2Code: 'LA',
    callingCode: '+856',
    flag: 'https://flagcdn.com/w320/la.png',
  },
  {
    name: 'Latvia',
    alpha2Code: 'LV',
    callingCode: '+371',
    flag: 'https://flagcdn.com/w320/lv.png',
  },
  {
    name: 'Lebanon',
    alpha2Code: 'LB',
    callingCode: '+961',
    flag: 'https://flagcdn.com/w320/lb.png',
  },
  {
    name: 'Lesotho',
    alpha2Code: 'LS',
    callingCode: '+266',
    flag: 'https://flagcdn.com/w320/ls.png',
  },
  {
    name: 'Liberia',
    alpha2Code: 'LR',
    callingCode: '+231',
    flag: 'https://flagcdn.com/w320/lr.png',
  },
  {
    name: 'Libya',
    alpha2Code: 'LY',
    callingCode: '+218',
    flag: 'https://flagcdn.com/w320/ly.png',
  },
  {
    name: 'Liechtenstein',
    alpha2Code: 'LI',
    callingCode: '+423',
    flag: 'https://flagcdn.com/w320/li.png',
  },
  {
    name: 'Lithuania',
    alpha2Code: 'LT',
    callingCode: '+370',
    flag: 'https://flagcdn.com/w320/lt.png',
  },
  {
    name: 'Luxembourg',
    alpha2Code: 'LU',
    callingCode: '+352',
    flag: 'https://flagcdn.com/w320/lu.png',
  },
  {
    name: 'Macau',
    alpha2Code: 'MO',
    callingCode: '+853',
    flag: 'https://flagcdn.com/w320/mo.png',
  },
  {
    name: 'Madagascar',
    alpha2Code: 'MG',
    callingCode: '+261',
    flag: 'https://flagcdn.com/w320/mg.png',
  },
  {
    name: 'Malawi',
    alpha2Code: 'MW',
    callingCode: '+265',
    flag: 'https://flagcdn.com/w320/mw.png',
  },
  {
    name: 'Malaysia',
    alpha2Code: 'MY',
    callingCode: '+60',
    flag: 'https://flagcdn.com/w320/my.png',
  },
  {
    name: 'Maldives',
    alpha2Code: 'MV',
    callingCode: '+960',
    flag: 'https://flagcdn.com/w320/mv.png',
  },
  {
    name: 'Mali',
    alpha2Code: 'ML',
    callingCode: '+223',
    flag: 'https://flagcdn.com/w320/ml.png',
  },
  {
    name: 'Malta',
    alpha2Code: 'MT',
    callingCode: '+356',
    flag: 'https://flagcdn.com/w320/mt.png',
  },
  {
    name: 'Marshall Islands',
    alpha2Code: 'MH',
    callingCode: '+692',
    flag: 'https://flagcdn.com/w320/mh.png',
  },
  {
    name: 'Martinique',
    alpha2Code: 'MQ',
    callingCode: '+596',
    flag: 'https://flagcdn.com/w320/mq.png',
  },
  {
    name: 'Mauritania',
    alpha2Code: 'MR',
    callingCode: '+222',
    flag: 'https://flagcdn.com/w320/mr.png',
  },
  {
    name: 'Mauritius',
    alpha2Code: 'MU',
    callingCode: '+230',
    flag: 'https://flagcdn.com/w320/mu.png',
  },
  {
    name: 'Mayotte',
    alpha2Code: 'YT',
    callingCode: '+262',
    flag: 'https://flagcdn.com/w320/yt.png',
  },
  {
    name: 'Mexico',
    alpha2Code: 'MX',
    callingCode: '+52',
    flag: 'https://flagcdn.com/w320/mx.png',
  },
  {
    name: 'Micronesia',
    alpha2Code: 'FM',
    callingCode: '+691',
    flag: 'https://flagcdn.com/w320/fm.png',
  },
  {
    name: 'Moldova',
    alpha2Code: 'MD',
    callingCode: '+373',
    flag: 'https://flagcdn.com/w320/md.png',
  },
  {
    name: 'Monaco',
    alpha2Code: 'MC',
    callingCode: '+377',
    flag: 'https://flagcdn.com/w320/mc.png',
  },
  {
    name: 'Mongolia',
    alpha2Code: 'MN',
    callingCode: '+976',
    flag: 'https://flagcdn.com/w320/mn.png',
  },
  {
    name: 'Montenegro',
    alpha2Code: 'ME',
    callingCode: '+382',
    flag: 'https://flagcdn.com/w320/me.png',
  },
  {
    name: 'Montserrat',
    alpha2Code: 'MS',
    callingCode: '+1664',
    flag: 'https://flagcdn.com/w320/ms.png',
  },
  {
    name: 'Morocco',
    alpha2Code: 'MA',
    callingCode: '+212',
    flag: 'https://flagcdn.com/w320/ma.png',
  },
  {
    name: 'Mozambique',
    alpha2Code: 'MZ',
    callingCode: '+258',
    flag: 'https://flagcdn.com/w320/mz.png',
  },
  {
    name: 'Myanmar',
    alpha2Code: 'MM',
    callingCode: '+95',
    flag: 'https://flagcdn.com/w320/mm.png',
  },
  {
    name: 'Namibia',
    alpha2Code: 'NA',
    callingCode: '+264',
    flag: 'https://flagcdn.com/w320/na.png',
  },
  {
    name: 'Nauru',
    alpha2Code: 'NR',
    callingCode: '+674',
    flag: 'https://flagcdn.com/w320/nr.png',
  },
  {
    name: 'Nepal',
    alpha2Code: 'NP',
    callingCode: '+977',
    flag: 'https://flagcdn.com/w320/np.png',
  },
  {
    name: 'Netherlands',
    alpha2Code: 'NL',
    callingCode: '+31',
    flag: 'https://flagcdn.com/w320/nl.png',
  },
  {
    name: 'New Caledonia',
    alpha2Code: 'NC',
    callingCode: '+687',
    flag: 'https://flagcdn.com/w320/nc.png',
  },
  {
    name: 'New Zealand',
    alpha2Code: 'NZ',
    callingCode: '+64',
    flag: 'https://flagcdn.com/w320/nz.png',
  },
  {
    name: 'Nicaragua',
    alpha2Code: 'NI',
    callingCode: '+505',
    flag: 'https://flagcdn.com/w320/ni.png',
  },
  {
    name: 'Niger',
    alpha2Code: 'NE',
    callingCode: '+227',
    flag: 'https://flagcdn.com/w320/ne.png',
  },
  {
    name: 'Nigeria',
    alpha2Code: 'NG',
    callingCode: '+234',
    flag: 'https://flagcdn.com/w320/ng.png',
  },
  {
    name: 'Niue',
    alpha2Code: 'NU',
    callingCode: '+683',
    flag: 'https://flagcdn.com/w320/nu.png',
  },
  {
    name: 'Norfolk Island',
    alpha2Code: 'NF',
    callingCode: '+672',
    flag: 'https://flagcdn.com/w320/nf.png',
  },
  {
    name: 'North Korea',
    alpha2Code: 'KP',
    callingCode: '+850',
    flag: 'https://flagcdn.com/w320/kp.png',
  },
  {
    name: 'North Macedonia',
    alpha2Code: 'MK',
    callingCode: '+389',
    flag: 'https://flagcdn.com/w320/mk.png',
  },
  {
    name: 'Northern Mariana Islands',
    alpha2Code: 'MP',
    callingCode: '+1670',
    flag: 'https://flagcdn.com/w320/mp.png',
  },
  {
    name: 'Norway',
    alpha2Code: 'NO',
    callingCode: '+47',
    flag: 'https://flagcdn.com/w320/no.png',
  },
  {
    name: 'Oman',
    alpha2Code: 'OM',
    callingCode: '+968',
    flag: 'https://flagcdn.com/w320/om.png',
  },
  {
    name: 'Pakistan',
    alpha2Code: 'PK',
    callingCode: '+92',
    flag: 'https://flagcdn.com/w320/pk.png',
  },
  {
    name: 'Palau',
    alpha2Code: 'PW',
    callingCode: '+680',
    flag: 'https://flagcdn.com/w320/pw.png',
  },
  {
    name: 'Palestine',
    alpha2Code: 'PS',
    callingCode: '+970',
    flag: 'https://flagcdn.com/w320/ps.png',
  },
  {
    name: 'Panama',
    alpha2Code: 'PA',
    callingCode: '+507',
    flag: 'https://flagcdn.com/w320/pa.png',
  },
  {
    name: 'Papua New Guinea',
    alpha2Code: 'PG',
    callingCode: '+675',
    flag: 'https://flagcdn.com/w320/pg.png',
  },
  {
    name: 'Paraguay',
    alpha2Code: 'PY',
    callingCode: '+595',
    flag: 'https://flagcdn.com/w320/py.png',
  },
  {
    name: 'Peru',
    alpha2Code: 'PE',
    callingCode: '+51',
    flag: 'https://flagcdn.com/w320/pe.png',
  },
  {
    name: 'Philippines',
    alpha2Code: 'PH',
    callingCode: '+63',
    flag: 'https://flagcdn.com/w320/ph.png',
  },
  {
    name: 'Pitcairn Islands',
    alpha2Code: 'PN',
    callingCode: '+64',
    flag: 'https://flagcdn.com/w320/pn.png',
  },
  {
    name: 'Poland',
    alpha2Code: 'PL',
    callingCode: '+48',
    flag: 'https://flagcdn.com/w320/pl.png',
  },
  {
    name: 'Portugal',
    alpha2Code: 'PT',
    callingCode: '+351',
    flag: 'https://flagcdn.com/w320/pt.png',
  },
  {
    name: 'Puerto Rico',
    alpha2Code: 'PR',
    callingCode: '+1787',
    flag: 'https://flagcdn.com/w320/pr.png',
  },
  {
    name: 'Qatar',
    alpha2Code: 'QA',
    callingCode: '+974',
    flag: 'https://flagcdn.com/w320/qa.png',
  },
  {
    name: 'Republic of the Congo',
    alpha2Code: 'CG',
    callingCode: '+242',
    flag: 'https://flagcdn.com/w320/cg.png',
  },
  {
    name: 'Réunion',
    alpha2Code: 'RE',
    callingCode: '+262',
    flag: 'https://flagcdn.com/w320/re.png',
  },
  {
    name: 'Romania',
    alpha2Code: 'RO',
    callingCode: '+40',
    flag: 'https://flagcdn.com/w320/ro.png',
  },
  {
    name: 'Russia',
    alpha2Code: 'RU',
    callingCode: '+73',
    flag: 'https://flagcdn.com/w320/ru.png',
  },
  {
    name: 'Rwanda',
    alpha2Code: 'RW',
    callingCode: '+250',
    flag: 'https://flagcdn.com/w320/rw.png',
  },
  {
    name: 'Saint Barthélemy',
    alpha2Code: 'BL',
    callingCode: '+590',
    flag: 'https://flagcdn.com/w320/bl.png',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2Code: 'SH',
    callingCode: '+290',
    flag: 'https://flagcdn.com/w320/sh.png',
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2Code: 'KN',
    callingCode: '+1869',
    flag: 'https://flagcdn.com/w320/kn.png',
  },
  {
    name: 'Saint Lucia',
    alpha2Code: 'LC',
    callingCode: '+1758',
    flag: 'https://flagcdn.com/w320/lc.png',
  },
  {
    name: 'Saint Martin',
    alpha2Code: 'MF',
    callingCode: '+590',
    flag: 'https://flagcdn.com/w320/mf.png',
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2Code: 'PM',
    callingCode: '+508',
    flag: 'https://flagcdn.com/w320/pm.png',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2Code: 'VC',
    callingCode: '+1784',
    flag: 'https://flagcdn.com/w320/vc.png',
  },
  {
    name: 'Samoa',
    alpha2Code: 'WS',
    callingCode: '+685',
    flag: 'https://flagcdn.com/w320/ws.png',
  },
  {
    name: 'San Marino',
    alpha2Code: 'SM',
    callingCode: '+378',
    flag: 'https://flagcdn.com/w320/sm.png',
  },
  {
    name: 'São Tomé and Príncipe',
    alpha2Code: 'ST',
    callingCode: '+239',
    flag: 'https://flagcdn.com/w320/st.png',
  },
  {
    name: 'Saudi Arabia',
    alpha2Code: 'SA',
    callingCode: '+966',
    flag: 'https://flagcdn.com/w320/sa.png',
  },
  {
    name: 'Senegal',
    alpha2Code: 'SN',
    callingCode: '+221',
    flag: 'https://flagcdn.com/w320/sn.png',
  },
  {
    name: 'Serbia',
    alpha2Code: 'RS',
    callingCode: '+381',
    flag: 'https://flagcdn.com/w320/rs.png',
  },
  {
    name: 'Seychelles',
    alpha2Code: 'SC',
    callingCode: '+248',
    flag: 'https://flagcdn.com/w320/sc.png',
  },
  {
    name: 'Sierra Leone',
    alpha2Code: 'SL',
    callingCode: '+232',
    flag: 'https://flagcdn.com/w320/sl.png',
  },
  {
    name: 'Singapore',
    alpha2Code: 'SG',
    callingCode: '+65',
    flag: 'https://flagcdn.com/w320/sg.png',
  },
  {
    name: 'Sint Maarten',
    alpha2Code: 'SX',
    callingCode: '+1721',
    flag: 'https://flagcdn.com/w320/sx.png',
  },
  {
    name: 'Slovakia',
    alpha2Code: 'SK',
    callingCode: '+421',
    flag: 'https://flagcdn.com/w320/sk.png',
  },
  {
    name: 'Slovenia',
    alpha2Code: 'SI',
    callingCode: '+386',
    flag: 'https://flagcdn.com/w320/si.png',
  },
  {
    name: 'Solomon Islands',
    alpha2Code: 'SB',
    callingCode: '+677',
    flag: 'https://flagcdn.com/w320/sb.png',
  },
  {
    name: 'Somalia',
    alpha2Code: 'SO',
    callingCode: '+252',
    flag: 'https://flagcdn.com/w320/so.png',
  },
  {
    name: 'South Africa',
    alpha2Code: 'ZA',
    callingCode: '+27',
    flag: 'https://flagcdn.com/w320/za.png',
  },
  {
    name: 'South Georgia',
    alpha2Code: 'GS',
    callingCode: '+500',
    flag: 'https://flagcdn.com/w320/gs.png',
  },
  {
    name: 'South Korea',
    alpha2Code: 'KR',
    callingCode: '+82',
    flag: 'https://flagcdn.com/w320/kr.png',
  },
  {
    name: 'South Sudan',
    alpha2Code: 'SS',
    callingCode: '+211',
    flag: 'https://flagcdn.com/w320/ss.png',
  },
  {
    name: 'Spain',
    alpha2Code: 'ES',
    callingCode: '+34',
    flag: 'https://flagcdn.com/w320/es.png',
  },
  {
    name: 'Sri Lanka',
    alpha2Code: 'LK',
    callingCode: '+94',
    flag: 'https://flagcdn.com/w320/lk.png',
  },
  {
    name: 'Sudan',
    alpha2Code: 'SD',
    callingCode: '+249',
    flag: 'https://flagcdn.com/w320/sd.png',
  },
  {
    name: 'Suriname',
    alpha2Code: 'SR',
    callingCode: '+597',
    flag: 'https://flagcdn.com/w320/sr.png',
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2Code: 'SJ',
    callingCode: '+4779',
    flag: 'https://flagcdn.com/w320/sj.png',
  },
  {
    name: 'Sweden',
    alpha2Code: 'SE',
    callingCode: '+46',
    flag: 'https://flagcdn.com/w320/se.png',
  },
  {
    name: 'Switzerland',
    alpha2Code: 'CH',
    callingCode: '+41',
    flag: 'https://flagcdn.com/w320/ch.png',
  },
  {
    name: 'Syria',
    alpha2Code: 'SY',
    callingCode: '+963',
    flag: 'https://flagcdn.com/w320/sy.png',
  },
  {
    name: 'Taiwan',
    alpha2Code: 'TW',
    callingCode: '+886',
    flag: 'https://flagcdn.com/w320/tw.png',
  },
  {
    name: 'Tajikistan',
    alpha2Code: 'TJ',
    callingCode: '+992',
    flag: 'https://flagcdn.com/w320/tj.png',
  },
  {
    name: 'Tanzania',
    alpha2Code: 'TZ',
    callingCode: '+255',
    flag: 'https://flagcdn.com/w320/tz.png',
  },
  {
    name: 'Thailand',
    alpha2Code: 'TH',
    callingCode: '+66',
    flag: 'https://flagcdn.com/w320/th.png',
  },
  {
    name: 'Timor-Leste',
    alpha2Code: 'TL',
    callingCode: '+670',
    flag: 'https://flagcdn.com/w320/tl.png',
  },
  {
    name: 'Togo',
    alpha2Code: 'TG',
    callingCode: '+228',
    flag: 'https://flagcdn.com/w320/tg.png',
  },
  {
    name: 'Tokelau',
    alpha2Code: 'TK',
    callingCode: '+690',
    flag: 'https://flagcdn.com/w320/tk.png',
  },
  {
    name: 'Tonga',
    alpha2Code: 'TO',
    callingCode: '+676',
    flag: 'https://flagcdn.com/w320/to.png',
  },
  {
    name: 'Trinidad and Tobago',
    alpha2Code: 'TT',
    callingCode: '+1868',
    flag: 'https://flagcdn.com/w320/tt.png',
  },
  {
    name: 'Tunisia',
    alpha2Code: 'TN',
    callingCode: '+216',
    flag: 'https://flagcdn.com/w320/tn.png',
  },
  {
    name: 'Turkey',
    alpha2Code: 'TR',
    callingCode: '+90',
    flag: 'https://flagcdn.com/w320/tr.png',
  },
  {
    name: 'Turkmenistan',
    alpha2Code: 'TM',
    callingCode: '+993',
    flag: 'https://flagcdn.com/w320/tm.png',
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2Code: 'TC',
    callingCode: '+1649',
    flag: 'https://flagcdn.com/w320/tc.png',
  },
  {
    name: 'Tuvalu',
    alpha2Code: 'TV',
    callingCode: '+688',
    flag: 'https://flagcdn.com/w320/tv.png',
  },
  {
    name: 'Uganda',
    alpha2Code: 'UG',
    callingCode: '+256',
    flag: 'https://flagcdn.com/w320/ug.png',
  },
  {
    name: 'Ukraine',
    alpha2Code: 'UA',
    callingCode: '+380',
    flag: 'https://flagcdn.com/w320/ua.png',
  },
  {
    name: 'United Arab Emirates',
    alpha2Code: 'AE',
    callingCode: '+971',
    flag: 'https://flagcdn.com/w320/ae.png',
  },
  {
    name: 'United Kingdom',
    alpha2Code: 'GB',
    callingCode: '+44',
    flag: 'https://flagcdn.com/w320/gb.png',
  },
  {
    name: 'United States',
    alpha2Code: 'US',
    callingCode: '+1201',
    flag: 'https://flagcdn.com/w320/us.png',
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2Code: 'UM',
    callingCode: '+268',
    flag: 'https://flagcdn.com/w320/um.png',
  },
  {
    name: 'United States Virgin Islands',
    alpha2Code: 'VI',
    callingCode: '+1340',
    flag: 'https://flagcdn.com/w320/vi.png',
  },
  {
    name: 'Uruguay',
    alpha2Code: 'UY',
    callingCode: '+598',
    flag: 'https://flagcdn.com/w320/uy.png',
  },
  {
    name: 'Uzbekistan',
    alpha2Code: 'UZ',
    callingCode: '+998',
    flag: 'https://flagcdn.com/w320/uz.png',
  },
  {
    name: 'Vanuatu',
    alpha2Code: 'VU',
    callingCode: '+678',
    flag: 'https://flagcdn.com/w320/vu.png',
  },
  {
    name: 'Vatican City',
    alpha2Code: 'VA',
    callingCode: '+3906698',
    flag: 'https://flagcdn.com/w320/va.png',
  },
  {
    name: 'Venezuela',
    alpha2Code: 'VE',
    callingCode: '+58',
    flag: 'https://flagcdn.com/w320/ve.png',
  },
  {
    name: 'Vietnam',
    alpha2Code: 'VN',
    callingCode: '+84',
    flag: 'https://flagcdn.com/w320/vn.png',
  },
  {
    name: 'Wallis and Futuna',
    alpha2Code: 'WF',
    callingCode: '+681',
    flag: 'https://flagcdn.com/w320/wf.png',
  },
  {
    name: 'Western Sahara',
    alpha2Code: 'EH',
    callingCode: '+2125288',
    flag: 'https://flagcdn.com/w320/eh.png',
  },
  {
    name: 'Yemen',
    alpha2Code: 'YE',
    callingCode: '+967',
    flag: 'https://flagcdn.com/w320/ye.png',
  },
  {
    name: 'Zambia',
    alpha2Code: 'ZM',
    callingCode: '+260',
    flag: 'https://flagcdn.com/w320/zm.png',
  },
  {
    name: 'Zimbabwe',
    alpha2Code: 'ZW',
    callingCode: '+263',
    flag: 'https://flagcdn.com/w320/zw.png',
  },
];
